### ISSUE TITLE
Modify routes

### ISSUE THREAD

**Issue by tz70s** [tz70s/pro-sy-kuo#7]
Currently, when we generate new statics into `docs/` folder. We still have to add some prefix, postfix.

 i.e.
The expected generation `http://127.0.0.1:9111/profile` -> `https://new.static.domain/html/profile.html`
Current generation `http://127.0.0.1:9111/profile` -> `https://new.static.domain/profile`

To improve this, I think the better way is to modify original route on `index.js` and the original prefix, postfix in `static/` folder.

i.e. 
`http://127.0.0.1:9111/profile` changed into `http://127.0.0.1:9111/html/profile.html`
The route of `index.js` should be modified too.

Can you do this? @r05921104

**Comment by r05921104** [comment]
Ok, willing to try it.

**Comment by r05921104** [comment]
I have a question.
Why do we need to modify index.js and the html files in static folder?
Can we just modify the sgen.py which changes the "http://127.0.0.1:9111/profile" in static folder into "https://new.static.domain/html/profile.html" in docs folder?

**Comment by tz70s** [comment]
Sure, we can make it in this way too, it depends on which way is convenient to us -> the `index.js` is only used on test. 
So, when we translate the prefix to the final static files, the consistent suffix may be more comfortable?
But you can choose the way you preferred though.
