### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by r05921104** [tz70s/pro-sy-kuo#9]
- [x] The color of the words need to be darker.

- [x] Add the logo of the national taiwan university and NTUEE. 

- [x] Add "Welcome to Sy-Yen Kuo personal web page.".

- [x] The profile needs to be partitioned into at least two paragraphs.

- [x] Make the buttons responsive or fix width of whole page. @tz70s

- [x] Font adjustment @tz70s

**Comment by tz70s** [comment]
Finished, close this out.
